### ISSUE TITLE
Broken in latest home assistant versions

### ISSUE THREAD

**Issue by Madj42** [prestomation/resmed_myair_sensors#26]
## Version of the custom_component
0.1.10

## Configuration

Configuration is done via wizard.

```

## Describe the bug
Component stopped working in latest versions.  When trying to remove and reads it, it displays the error below.

## Debug log

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/resmed_myair/client/new_client.py:247
Integration: ResMed myAir CPAP Sensors (documentation, issues)
First occurred: 7:08:01 PM (3 occurrences)
Last logged: 7:08:17 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/resmed_myair/config_flow.py", line 52, in async_step_user
    device: MyAirDevice = await get_device(
  File "/config/custom_components/resmed_myair/config_flow.py", line 32, in get_device
    device = await client.get_user_device_data()
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
TypeError: 'NoneType' object is not subscriptable




```text

Add your logs here.

```

**Comment by aurvandel** [comment]
I'm getting the same behavior.

**Comment by notmayo** [comment]
No longer working in 2022.12.X

**Comment by kellcomnet2** [comment]
Confirmed not working +1

**Comment by kellcomnet2** [comment]
‘’’
Unexpected error fetching myAir update data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/resmed_myair/coordinator.py", line 38, in _async_update_data
    self.device = await self.myair_client.get_user_device_data()
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
TypeError: 'NoneType' object is not subscriptable
‘’’

**Comment by prestomation** [comment]
Sorry folks. While I still use a ResMed CPAP, it has a CDMA radio and this network has been dismantled in my area. Due to this I am no longer able to effectively maintain this integration.

```
device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
TypeError: 'NoneType' object is not subscriptable
```
This implies that the ResMed website is now working differently than it used to and is unlikely to be related to HomeAssistant changes. Unfortunatly ResMed does not maintain a documented API so this integration works by reverse engineering the ResMed website and we are at their whim if they decide to change it.

Where are you all located? Has the myAir website changed for you? We previously saw that in Europe that 2FA email codes were required which was never implemented. Is this what you are seeing in your area now on the myAir website? This is something that someone would have to reverse engineer and figure out how to add to this integration

**Comment by kellcomnet2** [comment]
Interesting, when I just signed in to the website I had to agreed to a new user agreement and change my password, restarting ha to see if it loads any different

**Comment by kellcomnet2** [comment]
Ha pulled in latest data after logging into website, agreeing to terms, changing password then updating password in ha and restarting ha

**Comment by notmayo** [comment]
I'm in the US with a US account as well. I just logged into the app and had to accept another privacy or usage policy as well. This, like the other poster, resolved the error.

**Comment by kellcomnet2** [comment]
> I'm in the US with a US account as well. I just logged into the app and had to accept another privacy or usage policy as well. This, like the other poster, resolved the error.

So you didn’t have to change password? Interesting

**Comment by aurvandel** [comment]
Accepting the new TOS fixed it for me as well. Crazy that they updated the
same day I updated HA.

**Comment by Madj42** [comment]
Same here as well.
