### ISSUE TITLE
Integration is no longer fetching data

### ISSUE THREAD

**Issue by sh00t2kill** [prestomation/resmed_myair_sensors#42]
## Version of the custom_component
Version 0.1.11

## Describe the bug
All entities are unavailable

```
2024-05-19 21:54:40.868 ERROR (MainThread) [custom_components.resmed_myair.coordinator] Unexpected error fetching myAir update data                                    Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/coordinator.py", line 38, in _async_update_data
    self.device = await self.myair_client.get_user_device_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-05-19 21:54:42.972 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up resmed_myair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/coordinator.py", line 38, in _async_update_data
    self.device = await self.myair_client.get_user_device_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/resmed_myair/sensor.py", line 202, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 'NoneType' object is not subscriptable
```

**Comment by sh00t2kill** [comment]
Of course, I finally get around to lodging an issue and it started working.
Maybe it was a temporary resmed issue.
