### ISSUE TITLE
ResMed broke on HA Core 2024.8.1 or 2024.8.2

### ISSUE THREAD

**Issue by Anto79-ops** [prestomation/resmed_myair_sensors#48]
Hello,

thanks for your integration!

Been using this now for a couple of months, and its usually pretty quiet in the logs, but today i keep seeing this:

```
This error originated from a custom integration.

Logger: custom_components.resmed_myair.coordinator
Source: helpers/update_coordinator.py:354
integration: ResMed myAir CPAP Sensors (documentation, issues)
First occurred: 10:58:54 AM (23 occurrences)
Last logged: 9:59:16 PM

Unexpected error fetching myAir update data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/coordinator.py", line 38, in _async_update_data
    self.device = await self.myair_client.get_user_device_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
The integration seems to work depsite this, not sure why its logging this now, all of a sudden.

Cheers,

Running HAOS 

Core 2024.8.1
Supervisor 2024.08.0
Operating System 13.0
Frontend 20240809.0

ResMed 0.1.13

**Comment by Anto79-ops** [comment]
also saw this:

```
2024-08-14 21:29:15.377 ERROR (MainThread) [custom_components.resmed_myair.coordinator] Unexpected error fetching myAir update data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/coordinator.py", line 38, in _async_update_data
    self.device = await self.myair_client.get_user_device_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
             ~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
```

**Comment by Anto79-ops** [comment]
ok just updated to core 2024.8.2 I think its now officially broken:

```
This error originated from a custom integration.

Logger: custom_components.resmed_myair.coordinator
Source: helpers/update_coordinator.py:354
integration: ResMed myAir CPAP Sensors (documentation, issues)
First occurred: 11:42:42 AM (1 occurrences)
Last logged: 11:42:42 AM

Unexpected error fetching myAir update data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/coordinator.py", line 38, in _async_update_data
    self.device = await self.myair_client.get_user_device_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/resmed_myair/client/new_client.py", line 247, in get_user_device_data
    device = records_json["data"]["getPatientWrapper"]["fgDevices"][0]
             ~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
```

and 

```
Logger: homeassistant.helpers.entity_platform
Source: helpers/entity_platform.py:418
First occurred: 11:42:42 AM (1 occurrences)
Last logged: 11:42:42 AM

resmed_myair raises exception ConfigEntryNotReady in forwarded platform sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
```

**Comment by sh00t2kill** [comment]
confirmed that the PR above addresses the issues, manually deployed changes and its back up and working again.
